// Generated by CoffeeScript 1.3.3
(function() {
  var Auth;

  Auth = (function() {

    function Auth() {
      window.link.subscribe('auth.error', this.exception);
    }

    Auth.prototype.exception = function(exception) {
      return console.log(exception['message']);
    };

    return Auth;

  })();

  $(document).ready(function() {});

}).call(this);
