// Generated by CoffeeScript 1.3.3
(function() {
  var Link;

  Link = (function() {

    Link.connected = false;

    Link.transport = false;

    Link.callback_register = {};

    function Link(config) {
      this.config = config;
      this.connect();
    }

    Link.prototype.connect = function() {
      this.transport = new SockJS('http://live_messages:9999/updater/');
      this.transport.onopen = function() {
        return window.link.connected();
      };
      this.transport.onclose = function() {
        return window.link.disconnected();
      };
      return this.transport.onmessage = function() {
        return window.link.process_message();
      };
    };

    Link.prototype.connected = function() {
      return this.connected = true;
    };

    Link.prototype.disconnected = function() {
      return this.connected = false;
    };

    Link.prototype.process_message = function() {
      return console.log('OPPPA');
    };

    Link.prototype.register = function(callback, permanent) {};

    Link.prototype.query = function(params, callback) {
      var callback_name, data, message;
      if (typeof callback === 'function') {
        callback_name = this.register(callback, false);
      } else {
        callback_name = callback;
      }
      data = {
        'params': params,
        'name': callback_name
      };
      message = JSON.stringify(data);
      return this.transport.send(message);
    };

    return Link;

  })();

  $(document).ready(function() {
    return window.link = new Link({});
  });

}).call(this);
