// Generated by CoffeeScript 1.3.3
var OBJECT_TRIGGER, focus, triggered;

OBJECT_TRIGGER = "#";

triggered = false;

focus = false;

$(document).ready(function() {
  return $("#new_message").autocomplete({
    source: function(request, response) {
      var query_params;
      query_params = {
        'request': request.term
      };
      return window.link.query(query_params, response, true);
    },
    search: function() {
      if (!triggered) {
        return false;
      }
    },
    select: function(event, ui) {
      var pos, text;
      text = this.value;
      pos = text.lastIndexOf(OBJECT_TRIGGER);
      this.value = text.substring(0, pos) + ' ' + OBJECT_TRIGGER + ui.item.value;
      triggered = false;
      focus = false;
      return false;
    },
    focus: function(event, ui) {
      focus = this.value;
      event.preventDefault();
      return true;
    }
  }).bind('keyup', function() {
    var index, last, len, query, text;
    if (!focus) {
      text = this.value;
      len = text.length;
      if (triggered) {
        index = text.lastIndexOf(OBJECT_TRIGGER);
        query = text.substring(index + OBJECT_TRIGGER.length);
        return $(this).autocomplete("search", query);
      } else {
        last = text.substring(len - OBJECT_TRIGGER.length);
        return triggered = last === OBJECT_TRIGGER;
      }
    }
  });
});
