// Generated by CoffeeScript 1.3.3
(function() {
  var Messages,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Messages = (function(_super) {

    __extends(Messages, _super);

    Messages.extend(Spine.Events);

    function Messages() {
      this.on_show = __bind(this.on_show, this);
      Messages.__super__.constructor.apply(this, arguments);
      this.title = 'Журналы';
      this.form = new MessagesForm({
        el: ".message-form"
      });
      this.bind("enter", this.on_show);
    }

    Messages.prototype.on_show = function() {};

    return Messages;

  })(Spine.Controller);

  this.Messages = Messages;

}).call(this);
