// Generated by CoffeeScript 1.3.3
(function() {
  var Message,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Message = (function(_super) {

    __extends(Message, _super);

    function Message() {
      return Message.__super__.constructor.apply(this, arguments);
    }

    Message.configure("Message", "text", "purpose", "tags", "created");

    Message.extend(TransportModel);

    return Message;

  })(Spine.Model);

  this.Message = Message;

}).call(this);
